source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ABEmojiSearchView_Example', :exclusive => true do
  pod "ABEmojiSearchView", :path => "../"
end

target 'ABEmojiSearchView_Tests', :exclusive => true do
  pod "ABEmojiSearchView", :path => "../"

  
end
